version: '3.9'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: threadi
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      
  # pg-admin:
  #   image: dpage/pgadmin4:6
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_DEFAULT_PORT: 5555
  #   ports:
  #     - "5555:5555"
 

volumes:
  pg_data:
 